server:
  port: 8080
eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:8090/eureka
      defaultZone: ${EUREKA_URI:http://localhost:8070/eureka}
  instance:
    #hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
        - id: ms-catalogo-service
          uri: lb://ms-catalogo-service
          predicates:
            - Path=/categoria/**,/producto/**
          filters:
            - AuthFilter
        - id: ms-cliente-service
          uri: lb://ms-cliente-service
          predicates:
            - Path=/cliente/**
        - id: ms-procesamiento-pedidos-service
          uri: lb://ms-procesamiento-pedidos-service
          predicates:
            - Path=/pedido/**
        - id: ms-auth-service
          uri: lb://ms-auth-service
          predicates:
            - Path=/auth/**
        - id: ms-inventario-service
          uri: lb://ms-inventario-service
          predicates:
            - Path=/inventario/**
        - id: ms-proveedor-service
          uri: lb://ms-proveedor-service
          predicates:
            - Path=/proveedor/**
        - id: ms-carrito-service
          uri: lb://ms-carrito-service
          predicates:
            - Path=/carrito/**
        - id: ms-factura-service
          uri: lb://ms-factura-service
          predicates:
            - Path=/factura/**
        - id: ms-Pago-Service
          uri: lb://ms-Pago-Service
          predicates:
            - Path=/pago/**