server:
  port: ${PORT:${SERVER_PORT:0}}
springdoc:
  api-doc:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html
spring:
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    generate-ddl: true

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ms_producto
    username: root
    password:

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8070/eureka}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

resilience4j:
  circuitbreaker:
    instances:
      pedidoListarPorIdCB:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: TIME_BASED
        minimumNumberOfCalls: 4
        waitDurationInOpenState: 5s
        #recilencia agregada



